name: Docs

on:
  push:
    branches:
      -  main

jobs:
  rustdoc:
    name: Rustdoc
    runs-on: ubuntu-latest

    steps:
      - name: Install rsync 📚
        run: |
          sudo apt-get update && sudo apt-get install -y rsync

      - uses: actions/checkout@v3
        with:
          repository: 'dpsa-project/dpsa4fl'

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: stable

      - name: Create rustdoc
        run: cargo doc --all

      - name: Create CNAME
        run: |
          echo 'dpsa-project.github.io' > target/doc/CNAME

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          ssh-key: ${{ secrets.PAGES_DEPLOY_KEY }}
          branch: gh-pages
          folder: target/doc
          clean: true
          git-config-email: bot@dpsa-project.github.io
          repository-name: dpsa-project/dpsa-project.github.io
          commit-message: "Update"
          single-commit: true

